language: python
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    - graphviz
before_install:
  - pip install -U pip setuptools wheel
install:
  - travis_wait travis_retry pip install -r requirements.txt
script: "nosetests bayesian_diff_in_diff/tests"